### ISSUE TITLE
Heap-buffer-overflow when changing resolution to 320x200

### ISSUE THREAD

**Issue by isolinis** [nicolasgasco/42_cube3d#138] opened 2022-08-09 17:18 UTC
<img width="975" alt="Screen Shot 2022-08-09 at 6 53 40 PM" src="https://user-images.githubusercontent.com/65722944/183714907-72ec8d7d-da55-443f-82fd-23108b19b63b.png">
It might be related to the previous bug & it seems it happens with standard resolution values.
This is the map I was testing with:

NO ./assets/128x128/no_texture.xpm
EA ./assets/128x128/ea_texture.xpm
WE ./assets/128x128/we_texture.xpm
SO ./assets/128x128/so_texture.xpm
F 135,111,82
C 109,109,109

1111
1001
1001
10N1
1001
1001
1111_

**Comment by nicolasgasco** [comment] 2022-08-10 06:43
Closing this issue as it conceptually is a duplicate of: https://github.com/nicolasgasco/42_cub3d/issues/137

**Closed as completed by nicolasgasco** 2022-08-10 06:43 UTC
Labels: duplicate
